### Post bug
POST http://localhost:7071/api/bugs
Accept "application/json"

{
    "summary" : "Testing Bugreport API",
    "description" : "Testing to add an issue from API to GitHub"
}



### Post bug
POST http://localhost:7071/api/bugs
Accept "application/json"

{
    "summary" : "Test with options...",
    "description" : "lorem ipsum etc..."
}